# Generated by Django 4.2.2 on 2023-07-07 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_dynamic_list_in_templates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='monthsurlhistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urlhistory', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='clicking_history',
        ),
    ]
